[package]
name = "ssh_chat"
version = "0.1.0"
edition = "2024"

[dependencies]
markdown-ast = "0.1.1"
serde = { version = "1.0.228", features = ["derive"] }
ssh_ui = "0.4.1"
tokio = "1.49.0"
toml = "1.0.3"
